import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/layout/NavBar";
import Footer from "@/layout/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <NavBar />
          <main >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
